baseURL: "https://TehJUG.org/"
languageCode: "fa-IR"
title: "تهران‌جاگ (گروه برنامه‌نویسان جاوای تهران)"
theme: hugo-refresh-rtl
staticDir: "static"
disableKinds: ["taxonomyTerm", "RSS"]

# Legacy configuration for syntax highlighting
pygmentsUseClasses: true
pygmentsCodeFences: true

Taxonomies:
  tag: "tags"

enableRobotsTXT: True

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

params:
  # main params of the site
  description: "وب‌سایت رسمی تهران‌جاگ (گروه برنامه‌نویسان جاوای تهران)"
  images:
    - img/site-feature-image.jpg

  # features to minify files
  jsMinify: true
  jsFingerprint: true
  cssMinify: true
  cssFingerprint: true

  # option to specify the main colour of the theme
  mainColour: "#F39200"
  author: "تهران‌جاگ"
  favicon: "favicon.ico"
  og_image: "img/team/og_image.jpg"

  # summary options
  summary:
    defaultImage : "img/sessions/default_poster.jpg"

  # loading options
  loading:
    image: "images/rings.svg"

  # main pages options
  mainPage:
    fontFamily: "Shabnam"

  # sidebar options
  sidebar:
    logo: "logo/shirazlug_white.png"
    fontFamily: "Shabnam"
    tags: "همه برچسب‌ها"

  # navbar options
  navbar:
    fontFamily: "Shabnam"
    tags: "برچسب‌ها"
    menu: [

      {
        name: "home",
        title: "خانه",
        url: "/",
        weight: 8,
        icon: 'home'
      },
      {
        name: "sessions",
        title: "نشست‌های جاگ",
        url: "/sessions/",
        weight: 7,
        icon: 'th-list'
      },
      {
        name: "posts",
        title: "پست‌های آزاد",
        url: "/posts/",
        weight: 6,
        icon: 'clipboard'
      },
      {
        name: "events",
        title: "رویدادها",
        url: "/events/",
        weight: 5,
        icon: 'calendar'
      },
      {
        name: "team",
        title: "تیم اجرایی",
        url: "/team/",
        weight: 3,
        icon: 'users'
      },
      {
        name: "about",
        title: "درباره ما",
        url: "/about/",
        weight: 2,
        icon: 'info'
      },
      {
        name: "donations",
        title: "حمایت‌های مالی",
        url: "/donations/records",
        weight: 1,
        icon: 'link'
      },
      {
        name: "links",
        title: "لینک‌های مفید",
        url: "/links/",
        weight: 1,
        icon: 'link'
      },

    ]

  # 404 page options
  pagNotFound:
    # option to specify the main picture of the sidebar
    image: "logo/404.svg"
    # option to specify the title of the 404 page
    title: خطای ۴۰۴
    # option to specify the subtitle of the 404 page
    subtitle: صفحه مورد نظر شما یافت نشد
    # option to specify the width of the image in the 404 page
    imageWidth: 500px

  # homepage options
  homepage:
    # option to specify the title in the homepage
    title: "تهران‌جاگ"
    # option to specify the subtitle in the homepage
    subtitle: " (گروه برنامه‌نویسان جاوای تهران) "
    description: "به تهران‌جاگ خوش آمدید :) جاگ به معنی گروه برنامه‌نویسان جاوا است و از افراد مختلف که به منظور تبادل اطلاعات در حوزه‌ی برنامه‌نویسی جاوا دور هم جمع می‌شوند، تشکیل شده است. اگر تمایل دارید دانش خود را با دیگران به اشتراک بگذارید یا کنجکاوید تا از تکنولوژی‌های آزاد جدید اطلاعاتی کسب کنید و یا از بودن در کنار چند دوست فعال در این زمینه لذت می‌برید، با ما همراه شوید. در ضمن، شرکت در جلسات برای عموم آزاد و رایگان است."
    # Logo
    logo: "logo/shirazlug.svg"

    # Last Session Details
    lastSessionPoster: "img/sessions/poster221.jpg"
    lastSessionAlt: "Contributing to Free software"
    lastSessionNo: "221"

    imageWidth: 500px
    # Address
    address: "تهران"

  section:
    fontFamily: "Shabnam"

  # footer options
  footer:
    fontFamily: "Shabnam"
    logo: "logo/shirazlug_white.svg"
    copyright: "۱۴۰۱ - ۱۴۰۲ Ⓒ تهران‌جاگ"
    social: [
      {
        title: "contact@shirazlug.ir",
        icon: "fas fa-envelope",
        url: "mailto:contact@shirazlug.ir",
        weight: 7
      },
      {
        title: "گروه تلگرام",
        icon: "fab fa-telegram",
        url: "https://t.me/TehranJUG",
        weight: 6
      },
      {
        title: "ماستودون",
        icon: "fab fa-mastodon",
        rel: "me",
        url: "https://mastodon.social/",
        weight: 5
      },
      {
        title: "اینستاگرام",
        icon: "fab fa-instagram",
        url: "https://www.instagram.com/",
        weight: 4
      },
      {
        title: "توییتر",
        icon: "fab fa-twitter",
        url: "https://twitter.com/",
        weight: 3
      },
      {
        title: "لینکدین",
        icon: "fab fa-linkedin",
        url: "https://www.linkedin.com/in/",
        weight: 2
      },
      {
        title: "سورس کدها",
        icon: "fab fa-github",
        url: "https://github.com/TehJUG/tehjug.github.io",
        weight: 1
      }
    ]

